Adding local-config state
inkdropapp/api-docs pull request #13
Opened 2023-09-20 13:29 UTC by MayuBen1027

Adding the local-config state based on the inforation found [here](https://github.com/inkdropapp/docs/blob/master/src/pages/reference/state-local-config.md).

2023-09-20 19:23 UTC, Keisir commented
Thanks for the effort.

In its current form, I don't think this page adds any value. We need to check if there is any information we want to display on this page. Otherwise, in my opinion, it makes no difference in having this page.

Maybe Takuya has a hint what could be added here. I couldn't find anything in the type definitions.
https://github.com/inkdropapp/types/blob/main/packages/%40inkdropapp/redux-store/reducers/config.d.ts

2023-09-22 01:51 UTC, craftzdog commented
This state allows you to use config values of `config.json` in your react components.
It immediately reflects to the state whenever the config file is changed.
The data structure is same as the file content.
The type def currently looks like so:

```ts
import type { ValidateFunction } from 'ajv'
import ConfigSchema from '../json-schema/config.json'
import validator from '../validators/config'
export type NoteListSortBy = 'title' | 'updatedAt' | 'createdAt' | 'rank'
export type NoteListOrder = 'asc' | 'desc'
export type TagListOrder = 'name' | 'count'
export type Config = {
  _id: 'config'
  _rev?: string
  core: {
    defaultBook?: string
    noteListOrder?: NoteListOrder
    noteListSortBy?: NoteListSortBy
    tagListOrder?: TagListOrder
    queryOptions?: Record<
      string,
      {
        noteListOrder?: NoteListOrder
        noteListSortBy?: NoteListSortBy
      }
    >
  }
  updatedAt: number
}
const validateConfig: ValidateFunction<Config> = validator
export { ConfigSchema, validateConfig }
```

But I think we should cover the config module first: https://docs.inkdrop.app/reference/config

2023-09-22 01:58 UTC, craftzdog requested changes

2023-09-22 01:58 UTC, craftzdog commented on src/app/states/local-config/page.mdx
> +  description: 'An app state of the local config. This section explains how to fetch the `local config` state.',
❌ `local config`
⭕️ `localConfig`

2023-09-22 01:58 UTC, craftzdog commented on src/app/states/local-config/page.mdx
> +    Get the `local config` state manually:
❌ local config
⭕️ localConfig

2023-09-22 01:58 UTC, craftzdog commented on src/app/states/local-config/page.mdx
> +    const { config } = inkdrop.store.getState()
The doc was incorrect. It should be

```
const { localConfig } = inkdrop.store.getState()
```

2023-09-22 01:58 UTC, craftzdog commented on src/app/states/local-config/page.mdx
> +    const selector = ({ config }) => config
```
const selector = ({ localConfig }) => localConfig
```

2023-09-22 02:06 UTC, craftzdog commented
I guess the description of the data structure of the local config will not be so useful for developers because they are basically for the internal use.
It would be useful for plugins that have their own config values like:

```js
inkdrop.config.set('my-plugin.anInt', '123')
```

In this case, you can use `localConfig` like so:

```js
import { useSelector } from 'react-redux'
const selector = ({ localConfig }) => localConfig['my-plugin']
```

2023-11-30 00:57 UTC, closed without merging